/**
 * Build: compile every source in sources.json into one dist/app.js.
 *
 * The app used to ship its .jsx files raw and let Babel-standalone compile them
 * in the browser on every load — 2.4MB of compiler plus ~1.3s of CPU before a
 * single pad appeared. This does that work once, here.
 *
 *   node build.mjs            compile
 *   node build.mjs --check    exit 1 if dist/app.js is stale (used by CI)
 *
 * Sources stay as .jsx and are edited normally; only the output is generated.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync, statSync, readdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { transformSync } from '@babel/core';

const SOURCES = JSON.parse(readFileSync('sources.json', 'utf8'));
const OUT = 'dist/app.js';
const check = process.argv.includes('--check');

// A hash of every input; stamped into the bundle so --check can tell whether
// the committed output still matches the sources without recompiling blind.
const fingerprint = createHash('sha256');
for (const f of SOURCES) fingerprint.update(f).update(readFileSync(f));
const stamp = fingerprint.digest('hex').slice(0, 16);

if (check) {
  if (!existsSync(OUT)) {
    console.error('✗ dist/app.js is missing — run: ./build.sh');
    process.exit(1);
  }
  const built = readFileSync(OUT, 'utf8');
  if (!built.includes(`OA_BUILD_STAMP="${stamp}"`)) {
    console.error('✗ dist/app.js is STALE — sources changed since it was built.');
    console.error('  Run ./build.sh and commit the result.');
    process.exit(1);
  }
  console.log(`✓ dist/app.js is up to date (${stamp})`);
  process.exit(0);
}

const parts = [
  '/* GENERATED by build.mjs — do not edit. Edit the .jsx/.js sources instead. */',
  `window.OA_BUILD_STAMP="${stamp}";`,
  '(function(){"use strict";',
];

let jsx = 0, plain = 0, bytesIn = 0;
for (const file of SOURCES) {
  const code = readFileSync(file, 'utf8');
  bytesIn += code.length;
  parts.push(`\n/* ---- ${file} ---- */`);
  if (file.endsWith('.jsx')) {
    const out = transformSync(code, {
      filename: file,
      presets: [['@babel/preset-react', { runtime: 'classic' }]],
      compact: false,
      babelrc: false,
      configFile: false,
    });
    parts.push(out.code);
    jsx++;
  } else {
    parts.push(code);
    plain++;
  }
}
parts.push('})();');

mkdirSync('dist', { recursive: true });
const bundle = parts.join('\n');
writeFileSync(OUT, bundle);

const kb = (n) => `${(n / 1024).toFixed(0)}KB`;
console.log(`✓ ${OUT}  ${jsx} jsx + ${plain} js  ${kb(bytesIn)} in -> ${kb(bundle.length)} out  [${stamp}]`);

// ---------------------------------------------------------------------------
// Precache manifest: everything the running machine can possibly need, so the
// service worker can hold the whole thing and never touch the network again.
// ---------------------------------------------------------------------------
const walk = (dir, hit = []) => {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = `${dir}/${e.name}`;
    if (e.isDirectory()) walk(p, hit);
    else hit.push(p);
  }
  return hit;
};

const precache = [
  './',
  './index.html',
  './manifest.json',
  './dist/app.js',
  './vendor/react.production.min.js',
  './vendor/react-dom.production.min.js',
  ...walk('ICON and LOGO').map((p) => `./${p}`),
  ...(existsSync('SampleLibrary') ? walk('SampleLibrary') : [])
    .filter((p) => /\.(wav|mp3|ogg|flac)$/i.test(p))
    .map((p) => `./${p.split('/').map(encodeURIComponent).join('/')}`),
];

writeFileSync('dist/precache.json', JSON.stringify(precache, null, 1));
const bytes = precache
  .filter((p) => p !== './')
  .reduce((a, p) => {
    try { return a + statSync(decodeURIComponent(p.slice(2))).size; } catch (e) { return a; }
  }, 0);
console.log(`✓ dist/precache.json  ${precache.length} entries, ${kb(bytes)} held in cache`);
