/**
 * Build: compile every source in sources.json into one dist/app.js.
 *
 * The app used to ship its .jsx files raw and let Babel-standalone compile them
 * in the browser on every load — 2.4MB of compiler plus ~1.3s of CPU before a
 * single pad appeared. This does that work once, here.
 *
 *   node build.mjs            compile
 *   node build.mjs --check    exit 1 if dist/app.js is stale (used by CI)
 *
 * Sources stay as .jsx and are edited normally; only the output is generated.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync, statSync, readdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { transformSync } from '@babel/core';

const SOURCES = JSON.parse(readFileSync('sources.json', 'utf8'));
const OUT = 'dist/app.js';
const check = process.argv.includes('--check');

// A hash of every input; stamped into the bundle so --check can tell whether
// the committed output still matches the sources without recompiling blind.
const fingerprint = createHash('sha256');
for (const f of SOURCES) fingerprint.update(f).update(readFileSync(f));
const stamp = fingerprint.digest('hex').slice(0, 16);

if (check) {
  if (!existsSync(OUT)) {
    console.error('✗ dist/app.js is missing — run: ./build.sh');
    process.exit(1);
  }
  const built = readFileSync(OUT, 'utf8');
  if (!built.includes(`OA_BUILD_STAMP="${stamp}"`)) {
    console.error('✗ dist/app.js is STALE — sources changed since it was built.');
    console.error('  Run ./build.sh and commit the result.');
    process.exit(1);
  }
  console.log(`✓ dist/app.js is up to date (${stamp})`);
  process.exit(0);
}

// Human-readable release stamp shown in the footer: VYYYYMMDD.HHMM in UTC.
//
// Taken from the last COMMIT that touched a source file, not from the clock.
// Wall-clock time made every machine produce a different bundle, so CI's
// rebuild-and-commit step (.github/workflows/build.yml) saw a diff on every
// run and pushed a "Build: recompile dist/" commit after each push, forever.
// Keyed to the sources, the same commit always builds the same bytes, and a
// push that changes no source leaves the stamp alone.
const p2 = (n) => String(n).padStart(2, '0');
const stampFrom = (date) =>
  `V${date.getUTCFullYear()}${p2(date.getUTCMonth() + 1)}${p2(date.getUTCDate())}`
  + `.${p2(date.getUTCHours())}${p2(date.getUTCMinutes())}`;

let version;
try {
  // %cI = committer date, ISO-8601. Limited to the compiled sources plus this
  // script, so a README or workflow edit does not bump the release stamp.
  const iso = execFileSync(
    'git', ['log', '-1', '--format=%cI', '--', ...SOURCES, 'build.mjs', 'sources.json'],
    { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] },
  ).trim();
  version = iso ? stampFrom(new Date(iso)) : stampFrom(new Date());
} catch (e) {
  // No git (a source tarball, a stripped CI image) — fall back to build time.
  version = stampFrom(new Date());
}

const parts = [
  '/* GENERATED by build.mjs — do not edit. Edit the .jsx/.js sources instead. */',
  `window.OA_BUILD_STAMP="${stamp}";`,
  `window.OA_BUILD_VERSION="${version}";`,
  '(function(){"use strict";',
];

let jsx = 0, plain = 0, bytesIn = 0;
for (const file of SOURCES) {
  const code = readFileSync(file, 'utf8');
  bytesIn += code.length;
  let out = code;
  if (file.endsWith('.jsx')) {
    out = transformSync(code, {
      filename: file,
      presets: [['@babel/preset-react', { runtime: 'classic' }]],
      compact: false,
      babelrc: false,
      configFile: false,
    }).code;
    jsx++;
  } else {
    plain++;
  }
  // Each file gets its own scope, exactly as the separate <script> tags gave
  // it. Without this, top-level `const`s in different files collide — several
  // declare the same helper names. Cross-file sharing is via window.* only.
  parts.push(`\n/* ---- ${file} ---- */`);
  parts.push('(function(){');
  parts.push(out);
  parts.push('})();');
}
parts.push('})();');

mkdirSync('dist', { recursive: true });
const bundle = parts.join('\n');
writeFileSync(OUT, bundle);

const kb = (n) => `${(n / 1024).toFixed(0)}KB`;
console.log(`✓ ${OUT}  ${jsx} jsx + ${plain} js  ${kb(bytesIn)} in -> ${kb(bundle.length)} out  [${stamp}] ${version}`);

// ---------------------------------------------------------------------------
// Precache manifest: everything the running machine can possibly need, so the
// service worker can hold the whole thing and never touch the network again.
// ---------------------------------------------------------------------------
const walk = (dir, hit = []) => {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = `${dir}/${e.name}`;
    if (e.isDirectory()) walk(p, hit);
    else hit.push(p);
  }
  return hit;
};

const precache = [
  './',
  './index.html',
  './manifest.json',
  './dist/app.js',
  './vendor/react.production.min.js',
  './vendor/react-dom.production.min.js',
  ...walk('ICON and LOGO').map((p) => `./${p}`),
  ...(existsSync('SampleLibrary') ? walk('SampleLibrary') : [])
    .filter((p) => /\.(wav|mp3|ogg|flac)$/i.test(p))
    .map((p) => `./${p.split('/').map(encodeURIComponent).join('/')}`),
];

writeFileSync('dist/precache.json', JSON.stringify(precache, null, 1));
const bytes = precache
  .filter((p) => p !== './')
  .reduce((a, p) => {
    try { return a + statSync(decodeURIComponent(p.slice(2))).size; } catch (e) { return a; }
  }, 0);
console.log(`✓ dist/precache.json  ${precache.length} entries, ${kb(bytes)} held in cache`);
