/**
 * Service worker: hold the entire machine in cache so a running instance never
 * waits on the network. The precache list is generated by build.mjs into
 * ./dist/precache.json — app shell, vendored React, the compiled bundle and the
 * whole sample library.
 */
const CACHE = 'sampler-v3';

self.addEventListener('install', (e) => {
  e.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    let list = ['./', './index.html', './manifest.json', './dist/app.js'];
    try {
      const res = await fetch('./dist/precache.json', { cache: 'no-cache' });
      if (res.ok) list = await res.json();
    } catch (err) {}
    // Add individually: one 404 must not abandon the whole precache.
    await Promise.all(list.map((url) =>
      cache.add(new Request(url, { cache: 'reload' })).catch(() => {})));
    self.skipWaiting();
  })());
});

self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET') return;
  e.respondWith((async () => {
    const hit = await caches.match(e.request, { ignoreSearch: true });
    if (hit) return hit;
    try {
      const res = await fetch(e.request);
      // Fold anything new (a user's own samples) into the cache as it is used.
      if (res.ok && new URL(e.request.url).origin === self.location.origin) {
        const cache = await caches.open(CACHE);
        cache.put(e.request, res.clone());
      }
      return res;
    } catch (err) {
      if (e.request.mode === 'navigate') {
        const shell = await caches.match('./index.html');
        if (shell) return shell;
      }
      throw err;
    }
  })());
});
